name: Unit-testing
'on':
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "install"
        working-directory: ./app
        run: 'npm ci && npm test-ci'
